/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillasRouteImport } from './routes/villas'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VillasIndexRouteImport } from './routes/villas.index'
import { Route as VillasIdRouteImport } from './routes/villas.$id'

const VillasRoute = VillasRouteImport.update({
  id: '/villas',
  path: '/villas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VillasIndexRoute = VillasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VillasRoute,
} as any)
const VillasIdRoute = VillasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VillasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/villas': typeof VillasRouteWithChildren
  '/villas/$id': typeof VillasIdRoute
  '/villas/': typeof VillasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/villas/$id': typeof VillasIdRoute
  '/villas': typeof VillasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/villas': typeof VillasRouteWithChildren
  '/villas/$id': typeof VillasIdRoute
  '/villas/': typeof VillasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/villas'
    | '/villas/$id'
    | '/villas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/villas/$id' | '/villas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/villas'
    | '/villas/$id'
    | '/villas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  VillasRoute: typeof VillasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villas': {
      id: '/villas'
      path: '/villas'
      fullPath: '/villas'
      preLoaderRoute: typeof VillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villas/': {
      id: '/villas/'
      path: '/'
      fullPath: '/villas/'
      preLoaderRoute: typeof VillasIndexRouteImport
      parentRoute: typeof VillasRoute
    }
    '/villas/$id': {
      id: '/villas/$id'
      path: '/$id'
      fullPath: '/villas/$id'
      preLoaderRoute: typeof VillasIdRouteImport
      parentRoute: typeof VillasRoute
    }
  }
}

interface VillasRouteChildren {
  VillasIdRoute: typeof VillasIdRoute
  VillasIndexRoute: typeof VillasIndexRoute
}

const VillasRouteChildren: VillasRouteChildren = {
  VillasIdRoute: VillasIdRoute,
  VillasIndexRoute: VillasIndexRoute,
}

const VillasRouteWithChildren =
  VillasRoute._addFileChildren(VillasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  VillasRoute: VillasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
