/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VillasRouteImport } from './routes/villas'
import { Route as TravelStoriesRouteImport } from './routes/travel-stories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VillasIndexRouteImport } from './routes/villas.index'
import { Route as TravelStoriesIndexRouteImport } from './routes/travel-stories.index'
import { Route as VillasIdRouteImport } from './routes/villas.$id'
import { Route as TravelStoriesSlugRouteImport } from './routes/travel-stories.$slug'

const VillasRoute = VillasRouteImport.update({
  id: '/villas',
  path: '/villas',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelStoriesRoute = TravelStoriesRouteImport.update({
  id: '/travel-stories',
  path: '/travel-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VillasIndexRoute = VillasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VillasRoute,
} as any)
const TravelStoriesIndexRoute = TravelStoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TravelStoriesRoute,
} as any)
const VillasIdRoute = VillasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VillasRoute,
} as any)
const TravelStoriesSlugRoute = TravelStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TravelStoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/travel-stories': typeof TravelStoriesRouteWithChildren
  '/villas': typeof VillasRouteWithChildren
  '/travel-stories/$slug': typeof TravelStoriesSlugRoute
  '/villas/$id': typeof VillasIdRoute
  '/travel-stories/': typeof TravelStoriesIndexRoute
  '/villas/': typeof VillasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/travel-stories/$slug': typeof TravelStoriesSlugRoute
  '/villas/$id': typeof VillasIdRoute
  '/travel-stories': typeof TravelStoriesIndexRoute
  '/villas': typeof VillasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/travel-stories': typeof TravelStoriesRouteWithChildren
  '/villas': typeof VillasRouteWithChildren
  '/travel-stories/$slug': typeof TravelStoriesSlugRoute
  '/villas/$id': typeof VillasIdRoute
  '/travel-stories/': typeof TravelStoriesIndexRoute
  '/villas/': typeof VillasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/travel-stories'
    | '/villas'
    | '/travel-stories/$slug'
    | '/villas/$id'
    | '/travel-stories/'
    | '/villas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/travel-stories/$slug'
    | '/villas/$id'
    | '/travel-stories'
    | '/villas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/travel-stories'
    | '/villas'
    | '/travel-stories/$slug'
    | '/villas/$id'
    | '/travel-stories/'
    | '/villas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  TravelStoriesRoute: typeof TravelStoriesRouteWithChildren
  VillasRoute: typeof VillasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/villas': {
      id: '/villas'
      path: '/villas'
      fullPath: '/villas'
      preLoaderRoute: typeof VillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-stories': {
      id: '/travel-stories'
      path: '/travel-stories'
      fullPath: '/travel-stories'
      preLoaderRoute: typeof TravelStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villas/': {
      id: '/villas/'
      path: '/'
      fullPath: '/villas/'
      preLoaderRoute: typeof VillasIndexRouteImport
      parentRoute: typeof VillasRoute
    }
    '/travel-stories/': {
      id: '/travel-stories/'
      path: '/'
      fullPath: '/travel-stories/'
      preLoaderRoute: typeof TravelStoriesIndexRouteImport
      parentRoute: typeof TravelStoriesRoute
    }
    '/villas/$id': {
      id: '/villas/$id'
      path: '/$id'
      fullPath: '/villas/$id'
      preLoaderRoute: typeof VillasIdRouteImport
      parentRoute: typeof VillasRoute
    }
    '/travel-stories/$slug': {
      id: '/travel-stories/$slug'
      path: '/$slug'
      fullPath: '/travel-stories/$slug'
      preLoaderRoute: typeof TravelStoriesSlugRouteImport
      parentRoute: typeof TravelStoriesRoute
    }
  }
}

interface TravelStoriesRouteChildren {
  TravelStoriesSlugRoute: typeof TravelStoriesSlugRoute
  TravelStoriesIndexRoute: typeof TravelStoriesIndexRoute
}

const TravelStoriesRouteChildren: TravelStoriesRouteChildren = {
  TravelStoriesSlugRoute: TravelStoriesSlugRoute,
  TravelStoriesIndexRoute: TravelStoriesIndexRoute,
}

const TravelStoriesRouteWithChildren = TravelStoriesRoute._addFileChildren(
  TravelStoriesRouteChildren,
)

interface VillasRouteChildren {
  VillasIdRoute: typeof VillasIdRoute
  VillasIndexRoute: typeof VillasIndexRoute
}

const VillasRouteChildren: VillasRouteChildren = {
  VillasIdRoute: VillasIdRoute,
  VillasIndexRoute: VillasIndexRoute,
}

const VillasRouteWithChildren =
  VillasRoute._addFileChildren(VillasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  TravelStoriesRoute: TravelStoriesRouteWithChildren,
  VillasRoute: VillasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
